name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Setup AdoptOpenJDK 16"
        uses: "actions/setup-java@v2.1.0"
        with:
          distribution: "adopt"
          java-version: "16"
      - name: "Clean Build"
        run: "./gradlew clean build"
